services:
  - type: web
    name: applymate-backend
    env: python
    plan: free
    region: ohio
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn applymate.wsgi:application
    healthCheckPath: /api/health/
    autoDeploy: true
    rootDir: backend
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: "applymate-backend.onrender.com,*.onrender.com"
      - key: AI_PROVIDER
        value: "openai"
      - key: AI_API_KEY
        sync: false          
      - key: DATABASE_URL
        sync: false        
