# Generated by Django 5.0.6 on 2025-08-21 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Base Resume', max_length=120)),
                ('file', models.FileField(upload_to='resumes/')),
                ('parsed_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bullets', 'Bullets'), ('coverletter', 'CoverLetter'), ('resume', 'Resume')], max_length=20)),
                ('content_md', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_docs', to='jobs.jobposting')),
            ],
        ),
    ]
