# Generated by Django 5.0.6 on 2025-09-08 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_company_user_alter_jobposting_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_company_user_name'),
        ),
    ]
